using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NB.Core.Web.Models
{
    public class CompanyFinancialHighlights
    {

        //Fiscal Year
        /// <summary>
        /// The date of the end of the firm's accounting year.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks></remarks>
        public System.DateTime FiscalYearEnds { get; set; }
        /// <summary>
        /// Date for the most recent quarter end for which data is available on the Key Statistics page. This period is often abbreviated as "MRQ."
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks></remarks>
        public System.DateTime MostRecentQuarter { get; set; }

        //Profitability and Management Effectiveness
        /// <summary>
        /// Also known as Return on Sales, this value is the Net Income After Taxes for the trailing 12 months divided by Total Revenue for the same period and is expressed as a percentage.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: (Net Income / Total Revenues) x 100
        /// Trailing Twelve Months</remarks>
        public double ProfitMarginPercent { get; set; }
        /// <summary>
        /// This item represents the difference between the Total Revenues and the Total Operating Costs divided by Total Revenues, and is expressed as a percentage. Total Operating Costs consist of: (a) Cost of Goods Sold (b) Total (c) Selling, General &amp; Administrative Expenses (d) Total R &amp; D Expenses (e) Depreciation &amp; Amortization and (f) Total Other Operating Expenses, Total. A ratio used to measure a company's operating efficiency.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: [(Total Revenues - Total Operating Costs) / (Total Revenues)] x 100
        /// Trailing Twelve Months</remarks>
        public double OperatingMarginPercent { get; set; }
        /// <summary>
        /// This ratio shows percentage of Returns to Total Assets of the company. This is a useful measure in analyzing how well a company uses its assets to produce earnings.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Earnings from Continuing Operations / Average Total Equity
        /// Trailing Twelve Months</remarks>
        public double ReturnOnAssetsPercent { get; set; }
        /// <summary>
        /// This is a measure of the return on money provided by the firms' owners. This ratio represents Earnings from Continuing Operations divided by average Total Equity and is expressed as a percentage.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: [(Earnings from Continuing Operations) / Total Common Equity] x 100
        /// Trailing Twelve Months</remarks>
        public double ReturnOnEquityPercent { get; set; }

        //Income Statement
        /// <summary>
        /// The amount of money generated by a company's business activities. Also known as Sales.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Trailing Twelve Months</remarks>
        public double RevenueInMillion { get; set; }
        /// <summary>
        /// Revenue in relation to shares.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Total Revenues / Weighted Average Shares Outstanding
        /// Trailing Twelve Months</remarks>
        public double RevenuePerShare { get; set; }
        /// <summary>
        /// The growth of Quarterly Total Revenues from the same quarter a year ago.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: [(Qtrly Total Revenues x Qtrly Total Revenues (yr ago)) / Qtrly Total Revenues (yr ago)] x 100
        /// Year Over Year</remarks>
        public double QuarterlyRevenueGrowthPercent { get; set; }
        /// <summary>
        /// This item represents Total Revenues minus Cost Of Goods Sold, Total.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Trailing Twelve Months</remarks>
        public double GrossProfitInMillion { get; set; }
        /// <summary>
        /// The accounting acronym EBITDA stands for "Earnings Before Interest, Tax, Depreciation, and Amortization."
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Trailing Twelve Months</remarks>
        public double EBITDAInMillion { get; set; }
        /// <summary>
        /// This ratio shows percentage of Net Income to Common Excluding Extra Items less Earnings Of Discontinued Operations to Total Revenues. This is the dollar amount accruing to common shareholders for dividends and retained earnings.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Net Income - Preferred Dividend and Other Adjustments - Earnings Of Discontinued Operations - Extraordinary Item &amp; Accounting Change
        /// Trailing Twelve Months</remarks>
        public double NetIncomeAvlToCommonInMillion { get; set; }
        /// <summary>
        /// This is the Adjusted Income Available to Common Stockholders (based on Generally Accepted Accounting Principles, GAAP) for the trailing 12 months divided by the trailing 12 month weighted average shares outstanding. Diluted EPS uses diluted weighted average shares in the calculation, or the weighted average shares assuming all convertible securities are exercised.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: (Net Income - Preferred Dividend and Other Adjustments)/ Weighted Average Diluted Shares Outstanding
        /// Trailing Twelve Months</remarks>
        public double DilutedEPS { get; set; }
        /// <summary>
        /// The growth of Quarterly Net Income from the same quarter a year ago.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: [(Qtrly Net Income x Qtrly Net Income (yr ago)) / Qtrly Net Income (yr ago)] x 100
        /// Year Over Year</remarks>
        public double QuaterlyEarningsGrowthPercent { get; set; }

        //Balance Sheet and CashFlowStatement
        /// <summary>
        /// The Total Cash and Short-term Investments on the elance sheet as of the most recent quarter.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Most Recent Quarter</remarks>
        public double TotalCashInMillion { get; set; }
        /// <summary>
        /// This is the Total Cash plus Short Term Investments divided by the Shares Outstanding at the end of the most recent fiscal quarter.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Most Recent Quarter</remarks>
        public double TotalCashPerShare { get; set; }
        /// <summary>
        /// The Total Debt on the elance sheet as of the most recent quarter.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Short Term Borrowings + Current Portion of Long Term Debt + Current Portion of Capital Lease + Long Term Debt + Long Term Capital Lease + Finance Division Debt Current + Finance Division Debt Non Current
        /// Most Recent Quarter</remarks>
        public double TotalDeptInMillion { get; set; }
        /// <summary>
        /// This ratio is Total Debt for the most recent fiscal quarter divided by Total Shareholder Equity for the same period.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: [(Long-term Debt + Capital Leases + Finance Division Debt Non-Current + Short-term Borrowings + Current Portion of Long-term Debt + Current Portion of Capital Lease Obligation + Finance Division Debt Current) / (Total Common Equity + Total Preferred Equity)] x 100
        /// Most Recent Quarter</remarks>
        public double TotalDeptPerEquity { get; set; }
        /// <summary>
        /// This is the ratio of Total Current Assets for the most recent quarter divided by Total Current Liabilities for the same period.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Total Current Assets / Total Current Liabilities
        /// Most Recent Quarter</remarks>
        public double CurrentRatio { get; set; }
        /// <summary>
        /// This is defined as the Common Shareholder's Equity divided by the Shares Outstanding at the end of the most recent fiscal quarter.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Total Common Equity / Total Common Shares Outstanding
        /// Most Recent Quarter</remarks>
        public double BookValuePerShare { get; set; }
        /// <summary>
        /// Net cash used or generated in operating activities during the stated period of time. It reflects net impact of all operating activity transactions on the cash flow of the entity. This GAAP figure is taken directly from the company's Cash Flow Statement and might include significant non-recurring items.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: Net Income + Depreciation and Amortization, Total + Other Amortization + Other Non-Cash Items, Total + Change in Working Capital
        /// Trailing Twelve Months</remarks>
        public double OperatingCashFlowInMillion { get; set; }
        /// <summary>
        /// This figure is a normalized item that excludes non-recurring items and also takes into consideration cash inflows from financing activities such as debt or preferred stock issuances.
        /// </summary>
        /// <value></value>
        /// <returns></returns>
        /// <remarks>Formula: (EBIT + Interest Expense) x (1 x Tax Rate) + Depreciation &amp; Amort., Total + Other Amortization + Capital Expenditure + Sale (Purchase) of Intangible assets - Change in Net Working Capital + Pref. Dividends Paid + Total Debt Repaid + Total Debt Issued + Repurchase of Preferred + Issuance of Preferred Stock   -- [Where: Tax Rate = 0.375]
        /// Trailing Twelve Months</remarks>
        public double LeveredFreeCashFlowInMillion { get; set; }


        internal CompanyFinancialHighlights(System.DateTime fiscalYEnds, System.DateTime mostRecentQtr, double[] values)
        {
            this.FiscalYearEnds = fiscalYEnds;
            this.MostRecentQuarter = mostRecentQtr;

            this.ProfitMarginPercent = values[0];
            this.OperatingMarginPercent = values[1];

            this.ReturnOnAssetsPercent = values[2];
            this.ReturnOnEquityPercent = values[3];

            this.RevenueInMillion = values[4];
            this.RevenuePerShare = values[5];
            this.QuarterlyRevenueGrowthPercent = values[6];
            this.GrossProfitInMillion = values[7];
            this.EBITDAInMillion = values[8];
            this.NetIncomeAvlToCommonInMillion = values[9];
            this.DilutedEPS = values[10];
            this.QuaterlyEarningsGrowthPercent = values[11];

            this.TotalCashInMillion = values[12];
            this.TotalCashPerShare = values[13];
            this.TotalDeptInMillion = values[14];
            this.TotalDeptPerEquity = values[15];
            this.CurrentRatio = values[16];
            this.BookValuePerShare = values[17];

            this.OperatingCashFlowInMillion = values[18];
            this.LeveredFreeCashFlowInMillion = values[19];
        }

    }
}
